### ISSUE TITLE
warning: this clause cannot match because a previous clause at line 2 always matches

### ISSUE THREAD

**Issue by sfusato** [nikkomiu/phoenix_inline_svg#21]
I'm getting this warning thrown from all the view files in my Phoenix project multiple times per view file:
```
warning: this clause cannot match because a previous clause at line 2 always matches
```

This happened after digesting my static assets: `mix phx.digest`. Since my `svg` folder was in `/priv/static/svg`, the svg files were also (unnecessary) digested and gzipped so this resulted in files as: 
* `italy.svg`
* `italy.svg.gz`

I haven't looked in the source code to see how the pattern match is done, but I assume this is causing the *warnings*.

Steps to reproduce:
1. run `mix phx.digest`
2. run `mix compile --force` (we need to forcefully recompile, otherwise we won't notice it right away)

I have moved everything one level up in the meantime:
```
config :phoenix_inline_svg, dir: "/priv/svg/"
```

I suppose PR #20 will automatically fix this, although the SVG's will still be unnecessary digested thus adding a tiny bit of extra waiting time on that step.

**Comment by nikkomiu** [comment]
Fixed on v1.3.1. Please reopen this issue if there are still problems after updating.
