### ISSUE TITLE
Bump or relax floki version requirement?

### ISSUE THREAD

**Issue by eahanson** [nikkomiu/phoenix_inline_svg#26]
The floki dependency is currently set to `{:floki, "~> 0.21.0"}` but the current version of floki is `0.23.0`. 

What do you think about updating it to `"~> 0.23.0"` or even `"~> 0.21"` (which would match `0.21` all the way up to `0.99`?)

I tried relaxing it in my own fork (https://github.com/eahanson/phoenix_inline_svg/commit/a566f8da97d8bf9e5e77e927d6c5a55c2b95e4bd) and the tests pass and everything seemed to work. I'm happy to issue a PR if you're interested.

**Comment by nikkomiu** [comment]
I’m good with moving to `~> 0.21` or even just doing both together and moving to `~> 0.23`
