### ISSUE TITLE
Something is Askew...

### ISSUE THREAD

**Issue by jherdman** [nikkomiu/phoenix_inline_svg#28]
I've followed the installation instructions described here: https://github.com/nikkomiu/phoenix_inline_svg/blob/810a33db39903bd8e8a79471fda086cfd29fa742/lib/phoenix_inline_svg/helpers.ex#L7-L11.

I then added an SVG to `assets/svg`, and in my template:

```html
<%= svg_image("edit", "icons") %>
```

To which Phoenix errors:

```
Compiling 2 files (.ex)

== Compilation error in file lib/figgis_web/views/layout_view.ex ==
** (CompileError) lib/figgis_web/templates/layout/app.html.eex:48: undefined function svg_image/2
    (elixir) src/elixir_locals.erl:108: :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
    (elixir) src/elixir_locals.erl:109: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Using the "old style" I at least don't see this error.

Is there something missing in the instructions?

**Comment by msmithstubbs** [comment]
Similar issue was discussed here: https://github.com/nikkomiu/phoenix_inline_svg/issues/25#issuecomment-521411895

Try checking that SVG icons exist in `priv/static` before compiling.

**Comment by jherdman** [comment]
Closing. This is definitely a dupe of #25.
