### ISSUE TITLE
Evaluating Embedded EEx Tags in SVG Files

### ISSUE THREAD

**Issue by samgaw** [nikkomiu/phoenix_inline_svg#29]
I've a number of SVG files that have Eex tags embedded in them to display dynamic values. This works fine when the SVGs are inlined within the template but doesn't when using `svg_image()` as it is now.

Can you think of any approach or import order that would allow `<%= some_func() %>` tags to evaluated by the template engine as the template is being generated?

Thanks.

**Comment by nikkomiu** [comment]
I'm not aware of how you would do this easily because I believe that you would need to send the SVG through the template lib to get those tags parsed which currently isn't included. But a PR for the change is welcome!
