### ISSUE TITLE
Annoing floki warnings

### ISSUE THREAD

**Issue by gushonorato** [nikkomiu/phoenix_inline_svg#35]
Hey, how are you doing?

I see that this issue was fixed in commit https://github.com/nikkomiu/phoenix_inline_svg/commit/b920af17ab568a88b5493cd8d8651ba00e87dc3c. 

What about creating a new 1.3.2 release?

Cheers,
Gustavo

**Comment by nikkomiu** [comment]
Released. v1.3.2
