### ISSUE TITLE
Using in a LiveView

### ISSUE THREAD

**Issue by matthewp** [nikkomiu/phoenix_inline_svg#44]
Sorry if this is obvious (i'm a newbie). You can't do:

```
<%= PhoenixInlineSvg.Helpers.svg_image(@conn, "home") %>
```

in a LiveView, and svg_image doesn't accept `@socket`. Is there another way?

**Comment by eboskma** [comment]
Yes, you can use the endpoint module instead of `@conn`. So it would look something like this:

```elixir
<%= PhoenixInlineSvg.Helpers.svg_image(MyAppWeb.Endpoint, "home") %>
```

**Comment by matthewp** [comment]
Thanks!
