### ISSUE TITLE
Adding HTML attrs don't work with the macro generated svg_image functions

### ISSUE THREAD

**Issue by mhanberg** [nikkomiu/phoenix_inline_svg#9]
## Description

The docs claim that you should be able to use the "new" way, which involves creating functions for each of your svgs at compile time. 

This seems to work work only for the function signature `svg_image(image_name, collection_name)` and does not work when passing options.

This is the line of the generated functions https://github.com/nikkomiu/phoenix_inline_svg/blob/master/lib/phoenix_inline_svg/helpers.ex#L287

Looked at the commit history, and I think that the ability to pass HTML attrs to the function was added after the "new way", and wasn't implemented for both.

## Expected

I expect to be able to pass options to the macro generated functions.
I expect to not have to pass the collection name to the macro generated functions.

**Comment by mhanberg** [comment]
@nikkomiu Going to take a crack at this

**Comment by nikkomiu** [comment]
(May be somewhat pointless since you wrote the changes but) PR #13 is merged to master. @mhanberg do you want to test against the master branch of the repo?

**Comment by nikkomiu** [comment]
Released under v1.3.0
